package  com.example.demo.Entity.enums;

public enum Domain { FINANCE,HEALTH ,EDUCATION,E_COMMERCE,MARKETING,TOURISM,INDUSTRY, ENTERTAINMENT,TRANSPORTATION,ENVIRONMENT,PUBLICADMINISTRATOR, PROFESSIONALSERVICES
}
