// estimation.model.ts
import { Session } from "./session"; // Assurez-vous que ce chemin est correct

export class Estimation {
  id?: string; // Optional because it may be generated by the database
  estimate: number;
  session: Session;

  constructor(estimate: number, session: Session, id?: string) {
    this.estimate = estimate;
    this.session = session;
    if (id) {
      this.id = id;
    }
  }
}
